[project]
name = "erfassinator"
version = "0.1.0"
description = "Gesammeltes Erfassen aller Einsatzberichte in FWportal"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
]
